//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILS.Data
{//
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SILSEntities : DbContext
    {
        public SILSEntities()
            : base("name=SILSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<HoldingList> HoldingLists { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
